# Planning types:
uint8 ARM=0          # only plan for arm joints, base is fixed
uint8 WHOLE_BODY=1   # whole-body planning with contact end-effectors fixed w.r.t. reference frame
uint8 BASE_PLANAR=2  # plan for planar floating base (SE(2)) with arm fixed - for base placement

geometry_msgs/Pose base_start       # Current placement of the floating base
std_msgs/Float64MultiArray q_start  # Values for the controlled joints, in correct order

string device_type
geometry_msgs/Pose affordance_grasp_pose
geometry_msgs/Pose affordance_base_pose
string motion_type # revolute, linear
float64 radius     # for revolute, yaw around affordance_base_pose [m]
float64 arc        # for revolute [rad]

uint8 planning_mode                 # Planning mode
---
bool result                                     # Whether the problem was solved successfully
trajectory_msgs/JointTrajectory q_trajectory    # Joint trajectory (does not include base)
float64 final_cost                              # Final cost of motion planner, if available
---
float64 current_cost                # Current optimisation cost [not currently available]
